# Generated by Django 4.2.14 on 2024-08-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_avatar',
            field=models.CharField(blank=True, choices=[('avatar1.png', 'Male Avatar'), ('avatar2.png', 'Female Avatar')], max_length=100, null=True),
        ),
    ]
