# Generated by Django 4.2.14 on 2024-08-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
