# Generated by Django 5.1.1 on 2024-09-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_default_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
