# Generated by Django 4.2.14 on 2024-07-31 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_donation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disasterreport',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='disasterreport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.RemoveField(
            model_name='impacttracking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='support',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlockchainTransaction',
        ),
        migrations.DeleteModel(
            name='DisasterReport',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Engagement',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='ImpactTracking',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
