# Generated by Django 4.2.14 on 2024-08-12 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_comment_content_type_remove_comment_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='object_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_notifications', to='core.comment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='follow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_notifications', to='core.follow'),
        ),
        migrations.AddField(
            model_name='notification',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_notifications', to='core.poll'),
        ),
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_notifications', to='core.post'),
        ),
        migrations.AddField(
            model_name='notification',
            name='reaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reaction_notifications', to='core.reaction'),
        ),
        migrations.AddField(
            model_name='notification',
            name='repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repost_notifications', to='core.repost'),
        ),
    ]
