# Generated by Django 4.2.14 on 2024-08-18 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_comment_image_alter_post_hashtags_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='core.comment'),
        ),
        migrations.AddField(
            model_name='repost',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='core.comment'),
        ),
    ]
