# Generated by Django 4.2.14 on 2024-08-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bookmark_comment_repost_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
