# Generated by Django 4.2.14 on 2024-07-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_default_avatar_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_avatar',
            field=models.CharField(blank=True, choices=[('avatar 1.jpg', 'Male Avatar'), ('avatar 2.jpg', 'Female Avatar')], max_length=100, null=True),
        ),
    ]
