# Generated by Django 4.2.14 on 2024-09-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_avatar',
            field=models.URLField(blank=True, choices=[('http://res.cloudinary.com/lahri/image/upload/v1725138494/disax/uljz6lf0hbazo9cfzfse.png', 'Male Avatar'), ('http://res.cloudinary.com/lahri/image/upload/v1725138532/disax/zmvmlvh2stjd3nzb94ao.png', 'Female Avatar')], max_length=100, null=True),
        ),
    ]
