# Generated by Django 4.2.14 on 2024-08-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_reaction_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
