# Generated by Django 4.2.14 on 2024-08-12 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0008_remove_notification_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentobject',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content_object',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user'], name='core_bookma_user_id_7561a6_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['post'], name='core_bookma_post_id_6c1403_idx'),
        ),
        migrations.AddIndex(
            model_name='repost',
            index=models.Index(fields=['user'], name='core_repost_user_id_021a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='repost',
            index=models.Index(fields=['post'], name='core_repost_post_id_8646eb_idx'),
        ),
        migrations.AddIndex(
            model_name='repost',
            index=models.Index(fields=['poll'], name='core_repost_poll_id_d46264_idx'),
        ),
        migrations.AddIndex(
            model_name='repost',
            index=models.Index(fields=['created_at'], name='core_repost_created_e40df4_idx'),
        ),
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['user'], name='core_view_user_id_130ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['post'], name='core_view_post_id_430971_idx'),
        ),
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['poll'], name='core_view_poll_id_3dcb76_idx'),
        ),
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['created_at'], name='core_view_created_ab6571_idx'),
        ),
        migrations.DeleteModel(
            name='ContentObject',
        ),
    ]
