# Generated by Django 4.2.14 on 2024-08-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_reaction_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disaster_type',
            field=models.CharField(blank=True, choices=[('flood', 'Flood'), ('wildfire', 'Wildfire'), ('drought', 'Drought'), ('storm', 'Storm'), ('heatwave', 'Heatwave'), ('earthquake', 'Earthquake'), ('tsunami', 'Tsunami'), ('volcano', 'Volcanic Eruption'), ('landslide', 'Landslide'), ('tornado', 'Tornado'), ('hurricane', 'Hurricane'), ('cyclone', 'Cyclone'), ('pandemic', 'Pandemic'), ('epidemic', 'Epidemic'), ('avalanche', 'Avalanche'), ('blizzard', 'Blizzard'), ('hailstorm', 'Hailstorm'), ('sandstorm', 'Sandstorm'), ('sinkhole', 'Sinkhole'), ('locust', 'Locust Infestation'), ('oilspill', 'Oil Spill'), ('chemical', 'Chemical Hazard'), ('nuclear', 'Nuclear Disaster'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='gif',
            field=models.FileField(blank=True, null=True, upload_to='posts/gif/'),
        ),
    ]
