version: '3.12'

services:

  web:
    build: .
    command: npm run start:debug
    image: oauth
    volumes:
      - .:/oauth
      - node_modules:/oauth/node_modules
      - .env:/oauth/.env
    env_file:
      - ./.env
    ports:
      - 3000:3000
    container_name: oauth
    networks:
      - climatewavers
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3307:3306
    container_name: oauth.db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - climatewavers
  
volumes:
  mysql_data:
    name: "oauth"
  node_modules:
  .env:

networks:
  climatewavers:
    driver: bridge
    external: true
    name: climatewavers
