export const dummyUser = {
  id: 10,
  is_follower: true,
  first_name: "Admin",
  last_name: "Dev",
  username: "admin",
  email: "admin@dev",
  country: "Nigeria",
  state: "Lagos",
  profile_pic: "/img_frame_30156.png",
  password: "admin123",
  access_token: "edgyui359r8dgwhjryrrewvoiy8rjennbrrn",
};

export const dummyPost = [
  {
    id: 1,
    comment_count: 2,
    reaction_count: 6,
    view_count: 0,
    repost_count: 5,
    bookmark_count: 5,
    user: dummyUser,
    is_reacted: true,
    is_bookmarked: true,
    is_reposted: true,
    content: "Dummy post on climate wavers",
  },
  {
    id: 2,
    comment_count: 2,
    reaction_count: 4,
    view_count: 0,
    repost_count: 5,
    bookmark_count: 5,
    user: dummyUser,
    is_reacted: true,
    is_bookmarked: true,
    is_reposted: true,
    content: "First post on climate wavers",
  },
];

export const dummyCampaigns = [
  {
    image: "/campaign2.png",
    title: "Rise Above the Floods",
    details:
      "This campaign provides emergency relief, including food, shelter, and medical assistance, to families impacted by devastating floods.",
    raised: "10000",
    amount: "15000",
    location: "",
    disaster: "",
    date: "",
  },
  {
    image: "/campaign1.png",
    title: "Wildfire Relief: Healing the Earth",
    details:
      "Our team works closely with local forestry agencies to replant trees and rehabilitate ecosystems affected by wildfires.",
    raised: "16000",
    amount: "20000",
    location: "",
    disaster: "",
    date: "",
  },
  {
    image: "/campaign4.png",
    title: "Volcano Resilience: Rebuilding Lives",
    details:
      "This campaign provides immediate relief, long-term recovery, and education on volcanic safety measures.",
    raised: "32000",
    amount: "50000",
    location: "",
    disaster: "",
    date: "",
  },
  {
    image: "/campaign3.png",
    title: "QuakeSafe: Earthquake Preparedness",
    details:
      "We collaborate with engineers and local governments to strengthen buildings, bridges, and critical infrastructure against earthquakes.",
    raised: "14000",
    amount: "25000",
    location: "",
    disaster: "",
    date: "",
  },
  {
    image: "/campaign10.png",
    title: "Drought Resilience: Water for All",
    details:
      "Droughts threaten agriculture, health, and livelihoods. This campaign focuses on water conservation, rainwater harvesting, and community training to mitigate the impact of prolonged dry spells.",
    raised: "100000",
    amount: "150000",
    location: "",
    disaster: "",
    date: "",
  },
  {
    image: "/campaign9.png",
    title: "Tornado Relief: Rebuilding Homes",
    details:
      "Tornadoes leave devastation in their wake. We provide emergency shelter, food, and psychological support to affected communities. Our goal is to rebuild homes and restore hope.",
    raised: "15000",
    amount: "20000",
    location: "",
    disaster: "",
    date: "",
  },
  {
    image: "/campaign5.png",
    title: "Glacier Retreat Awareness",
    details:
      "Glaciers are shrinking due to global warming. This campaign raises awareness through documentaries, workshops, and field trips. Let’s protect our icy giants!",
    raised: "21000",
    amount: "32000",
    location: "",
    disaster: "",
    date: "",
  },
  {
    image: "/campaign7.png",
    title: "Typhoon Resilience: Preparedness Kits",
    details:
      "Typhoons can be catastrophic. We assemble disaster kits containing essentials like food, water, and first aid supplies. Your donation ensures families are ready when the next storm hits.",
    raised: "17000",
    amount: "26000",
    location: "",
    disaster: "",
    date: "",
  },
  {
    image: "/campaign1.png",
    title: "Heatwave Relief: Cooling Centers",
    details:
      "Heatwaves endanger vulnerable populations. This campaign establishes cooling centers, distributes fans, and educates communities on heat-related health risks.",
    raised: "1500",
    amount: "10000",
    location: "",
    disaster: "",
    date: "",
  },
  {
    image: "/campaign11.png",
    title: "Avalanche Safety: Mountain Communities",
    details:
      "In snow-covered regions, avalanches pose serious threats. We train locals in avalanche safety, provide rescue equipment, and promote risk reduction strategies.",
    raised: "35000",
    amount: "42000",
    location: "",
    disaster: "",
    date: "",
  },
  {
    image: "/campaign8.png",
    title: "Cyclone Recovery: Rebuilding Schools",
    details:
      "Cyclones damage schools, disrupting children’s education. This campaign focuses on rebuilding classrooms, providing books, and creating safe learning environments.",
    raised: "90000",
    amount: "150000",
    location: "",
    disaster: "",
    date: "",
  },
  {
    image: "/campaign6.png",
    title: "Landslide Prevention: Slope Stabilization",
    details:
      "Landslides endanger lives and property. We work with geologists to stabilize slopes, plant vegetation, and educate residents on early warning signs.",
    raised: "36000",
    amount: "95000",
    location: "",
    disaster: "",
    date: "",
  },
];
